<H1> NUMPY</H1>

In [ ]:
import numpy as np

In [ ]:
a1 = np.arange(2,20,2)  #arange is used to create an array(range,step)
a1

In [ ]:
a2 = 2 * np.arange(2,22,2) 
a2

In [ ]:
type(a2)

In [ ]:
a2.shape

In [ ]:
a2.reshape(5,2) #to change order of an array

In [ ]:
type(a2)

In [ ]:
a2.dtype

In [ ]:
a3 = np.arange(3,5,dtype='float64')
a3

In [ ]:
a = [2,4,5,6,8] #list
a5 = np.array(a)
a5

In [ ]:
a = np.array([0.123456789121212,2,3], dtype=np.float16)
print("16bit: ", a[0])

a = np.array([0.123456789121212,2,3], dtype=np.float32)
print("32bit: ", a[0])

b = np.array([0.123456789121212121212,2,3], dtype=np.float64)
print("64bit: ", b[0])

In [ ]:
b = [[2,4,1],[3,6.3,5],[3,7,9.5]]
a6 = np.array(b)
a6

In [ ]:
dt = np.dtype([('age','int32'),('name','U5')])  #age is of int32 bits size and name is of 5 characters
a7 = np.array([(21.4,'ramkrishna'),(13,'sss')],dtype=dt) 

In [ ]:
a7

### slicing

In [27]:
a8 = np.array([[34,56,23],[56,95,12],[45,90,56]])
a8

array([[34, 56, 23],
       [56, 95, 12],
       [45, 90, 56]])

In [28]:
a8[2][1]

90

In [29]:
a8[0][2]

23

In [30]:
a8[0:2,0:1]   #[rows,columns]

array([[34],
       [56]])

In [32]:
a8[0:2,1:2]

array([[56],
       [95]])

In [35]:
a8[1:,2:]

array([[12],
       [56]])

In [36]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.zeros([1,2,3])    #[no of arrays,rows,columns]

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
np.zeros([2,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
np.ones([3,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [40]:
np.eye(4)    #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.pi #pi value

3.141592653589793

In [42]:
np.e #exponential value

2.718281828459045

In [43]:
import math    #tau value
math.tau

6.283185307179586

In [44]:
np.linspace(2,5)      #it will divide between the range ito 50 equal parts by default

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [45]:
np.linspace(2,5,10) #it will divide in 10 parts

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [46]:
a = np.linspace(2,5,10,endpoint = False) #not getting end point i.e 5.
a

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7])

In [47]:
np.linspace(2,100,5,retstep = True)  #shows the difference of two outputs (all outputs)

(array([  2. ,  26.5,  51. ,  75.5, 100. ]), 24.5)

In [49]:
np.linspace(2,10,10)

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [48]:
np.logspace(2,10,10)    #to find the log values default base is 10

array([1.00000000e+02, 7.74263683e+02, 5.99484250e+03, 4.64158883e+04,
       3.59381366e+05, 2.78255940e+06, 2.15443469e+07, 1.66810054e+08,
       1.29154967e+09, 1.00000000e+10])

In [50]:
np.logspace(2,10,10,base = 2)   #base 2

array([   4.        ,    7.4069977 ,   13.71590373,   25.39841683,
         47.03150375,   87.09056001,  161.26989439,  298.63143413,
        552.99058631, 1024.        ])

In [51]:
np.log10(2)        #base is 10

0.3010299956639812

In [52]:
np.array([1,2,3,4]) / np.array([1,2,3,4])   #division

array([1., 1., 1., 1.])

In [54]:
a8

array([[34, 56, 23],
       [56, 95, 12],
       [45, 90, 56]])

In [53]:
 for i in np.nditer(a8):     #nditer is used for iteratoins 
        print(i)

34
56
23
56
95
12
45
90
56


In [55]:
a = np.random.rand(2,5)   #randomly generates the array between 0 and 1 of size 2*5
a

array([[0.88768769, 0.54430783, 0.81954451, 0.93410916, 0.88233207],
       [0.86158495, 0.75188915, 0.61072587, 0.60526222, 0.90703675]])

In [56]:
a1 = np.random.randn(2,5)  #randomly generates the array in negatives of size 2*5
a1

array([[ 1.36697884, -1.00648233, -1.3146801 ,  1.13886008, -0.10749933],
       [-1.02194869,  0.5303112 , -0.14231391, -1.79231956,  0.72755939]])

In [57]:
a2 = np.random.randint(1,6,size = (3,3))   #only integers value
a2

array([[3, 1, 1],
       [4, 4, 5],
       [5, 2, 1]])

In [58]:
a3 = np.array([[3,6,7]])
a4 = np.concatenate((a2,a3))
a4

array([[3, 1, 1],
       [4, 4, 5],
       [5, 2, 1],
       [3, 6, 7]])

In [59]:
a5 = np.array([[3],[6],[7]])
a6 = np.concatenate((a2,a5),axis = 1)
a6

array([[3, 1, 1, 3],
       [4, 4, 5, 6],
       [5, 2, 1, 7]])

### Broadcasting

In [60]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b = np.matrix([[100,100,100],[100,100,100],[100,100,100]])

a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
b

matrix([[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]])

In [62]:
a+b

matrix([[101, 102, 103],
        [104, 105, 106],
        [107, 108, 109]])

In [63]:
a-b

matrix([[-99, -98, -97],
        [-96, -95, -94],
        [-93, -92, -91]])

In [64]:
c = np.matrix([100,100,100])

In [65]:
c

matrix([[100, 100, 100]])

In [66]:
a+c

matrix([[101, 102, 103],
        [104, 105, 106],
        [107, 108, 109]])

In [67]:
b+c

matrix([[200, 200, 200],
        [200, 200, 200],
        [200, 200, 200]])

In [68]:
d = np.matrix([100])

In [69]:
d

matrix([[100]])

In [72]:
type(d)

numpy.matrixlib.defmatrix.matrix

In [70]:
a+d

matrix([[101, 102, 103],
        [104, 105, 106],
        [107, 108, 109]])

In [71]:
b+d

matrix([[200, 200, 200],
        [200, 200, 200],
        [200, 200, 200]])

In [84]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [85]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [86]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])